INSERT IGNORE INTO aircraft VALUES (1, 1, "NZC", "BOEING 787-9",         "");
INSERT IGNORE INTO aircraft VALUES (2, 2, "NZD", "BOEING 787-9",         "");
INSERT IGNORE INTO aircraft VALUES (3, 3, "NZE", "BOEING 787-9",         "");
INSERT IGNORE INTO aircraft VALUES (4, 4, "OAB", "Airbus A320-232",      "");
INSERT IGNORE INTO aircraft VALUES (5, 5, "OJB", "Airbus A320-232",      "");
INSERT IGNORE INTO aircraft VALUES (6, 6, "NEA", "Bombardier DHC-8-311", "");
INSERT IGNORE INTO aircraft VALUES (7, 7, "NEB", "Bombardier DHC-8-311", "");
INSERT IGNORE INTO aircraft VALUES (8, 8, "NEC", "Bombardier DHC-8-311", "");

INSERT IGNORE INTO seat VALUES (1,  1,    "1A", 1);
INSERT IGNORE INTO seat VALUES (2,  null, "1A", 2);
INSERT IGNORE INTO seat VALUES (3,  3,    "1A", 3);
INSERT IGNORE INTO seat VALUES (4,  4,    "1A", 4);
INSERT IGNORE INTO seat VALUES (5,  5,    "1A", 5);
INSERT IGNORE INTO seat VALUES (6,  6,    "1A", 6);
INSERT IGNORE INTO seat VALUES (7,  7,    "1A", 7);
INSERT IGNORE INTO seat VALUES (8,  null, "1A", 8);
INSERT IGNORE INTO seat VALUES (9,  null, "1B", 8);
INSERT IGNORE INTO seat VALUES (10, null, "1C", 8);
--INSERT IGNORE INTO seat VALUES (11, 8,    "1D", 8);